---
- name: Install dependencies
  package:
    name:
      - tar
      - gzip
  register: helm_install_dependencies_result
  until: helm_install_dependencies_result is success
  retries: 10
  delay: 2

- name: Get Helm artifact checksum
  uri:
    url: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz.sha256"
    return_content: true
  register: helm_checksum_result
  retries: 10

- name: Create temporary directory
  tempfile:
    state: directory
    suffix: helm
  register: helm_tempdir

- name: Download Helm dist archive
  get_url:
    url: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "{{ helm_tempdir.path }}/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    checksum: "sha256:{{ helm_checksum_result.content | regex_search('^[0-9a-f]{64}') }}"
    mode: 0644
  retries: 10

- name: Unpack Helm dist archive
  unarchive:
    remote_src: true
    src: "{{ helm_tempdir.path }}/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "{{ helm_tempdir.path }}/"

- name: Install Helm binary
  copy:
    remote_src: true
    src: "{{ helm_tempdir.path }}/linux-amd64/helm"
    dest: /usr/local/bin/helm
    mode: 0755
  retries: 10

- name: Cleanup installation files
  file:
    path: "{{ helm_tempdir.path }}"
    state: absent
