---
- hosts: k8s
  roles:
    - docker
    - k8s-kubespray
    - k8s
  vars:
   docker_storage_setup: False
   docker_storage_type: disk
   docker_storage_device: /dev/sdb1 
   docker_storage_location: /data/docker
   selinux_reboot_required: True
  pre_tasks:
   - name: configure create vg for docker
     block:
      - name: partition /sdb
        command: parted --script /dev/sdb mklabel gpt mkpart primary 1MiB 100%
        args:
          creates: /dev/sdb1      
      #- name: Ensure Volume Group vg_docker Exist
      #  lvg:
      #   vg: "vg_docker"
      #   pvs: "/dev/sdb1"
     when: docker_storage_setup