---
- hosts: k8s
  roles:
    #- docker
    #- k8s-kubespray
    - k8s
  vars:
   docker_storage_setup: False
   docker_storage_type: disk
   docker_storage_device: /dev/sdb1 
   docker_storage_location: /data/docker
   selinux_reboot_required: True
