vsphere_dns_servers:
  - "10.10.10.11"
  - "8.8.8.8"

esxi_hosts: 10.10.10.5
 
vsphere_vcenter_cluster: gabby-cluster 
vsphere_linux_vapp_template_name: centos-7-template-esxi
vsphere_vcenter_datacenter: gabby.local
vsphere_disk_datastore: datastore
terraform_dir: /root/terraform

vsphere_disk_cluster_datastore: "DatastoreCluster"
vsphere_vcenter: "10.10.10.15"
vcenter_user: "administrator@gabby.local"
vcenter_password: "P@ssw0rd"
vcenter_datacenter: "gabby.local"
vsphere_server: "10.10.10.15"
