#
---
# create install dirs
- debug: var=harbor_install_tmp
- debug: var=harbor_install_dir

- name: create install dir1
  file: 
    path: '{{ harbor_install_tmp }}'
    state: directory

- name: create install dir2
  file:
    path: '{{ harbor_install_dir }}'
    state: directory

# download or upload tarball
- name: Download file from URL
  get_url:
    url: "{{ harbor_install_download }}"
    dest: "{{ harbor_install_tmp }}/{{ harbor_install_tgz }}"

#- name: upload local copy
#  copy: 
#    src: '{{ harbor_install_upload_localcopy_of_installer }}'
#    dest: '{{ harbor_install_tmp }}/{{ harbor_install_tgz }}'

# unpack 
- name: unpack harbor_install_tgz
  unarchive: 
    remote_src: True
    src: '{{ harbor_install_tmp }}/{{ harbor_install_tgz }}'
    dest: '{{ harbor_install_dir }}'

# config template
- name: upload harbor.yml from template
  template: 
    src: harbor.yml.j2
    dest: '{{ harbor_install_dir }}/harbor/harbor.yml'

# run installer

- name: run harbor install script
  command: '{{harbor_install_dir}}/harbor/install.sh'
  #command: '{{harbor_install_dir}}/harbor/install.sh > {{ harbor_install_dir }}/harbor_install_log.txt'
  args:
    chdir: '{{ harbor_install_dir }}/harbor'
    # don't reinstall / figure out what when wrong and delete or move the logfile
    creates: '{{ harbor_install_dir }}/harbor_install_log.txt'

