# ssh-keygen -f /etc/heketi/heketi_key -t rsa -N ''
# chown heketi:heketi /etc/heketi/heketi_key*
# ssh-copy-id -i /etc/heketi/heketi_key.pub root@[glustera|glusterb|glusterc]

apiVersion: storage.k8s.io/v1beta1
kind: StorageClass  
metadata:
  name: heketi  
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs   
parameters:
  resturl: "http://10.10.10.70:8080"  
  restuser: "admin"  
  restuserkey: "$PASSWORD_ADMIN"
  
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: heketi-pvc 
 annotations:
   volume.beta.kubernetes.io/storage-class: heketi  
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 4Gi
     
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: heketi