---
galaxy_info:
  role_name: helm
  author: Claude Léveillé
  description: Installs Kubernetes Helm

  license: license (MIT)

  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - development
    - packaging
    - helm
    - kubernetes
    - cloud
    - container
    - docker
    - devops
    - ubuntu
    - debian
    - centos
    - alpine
    - fedora
    - ci
    - cd

dependencies: []
